import { Pitch } from "./types";

export const pitches: Pitch[] = [
  {
    id: '1',
    company_id: '1',
    name: 'Cancha Sintética La 14',
    type: 'Fútbol 5',
    zone: 'Norte',
    distance: '1.2 km',
    rating: '4.8',
    reviews: 120,
    price: '$90.000',
    price_per_hour: 90000,
    image: '/pasto-pitch-collection.png',
    image_url: '/pasto-pitch-collection.png',
    tone: 'field-emerald',
    amenity: 'Luces LED',
    amenities: 'Luces LED',
    open: true,
    surface: 'Sintética',
    size: '5 vs 5',
    created_at: new Date().toISOString()
  },
  {
    id: '2',
    company_id: '1',
    name: 'Complejo Deportivo El Lago',
    type: 'Fútbol 8',
    zone: 'Sur',
    distance: '3.5 km',
    rating: '4.9',
    reviews: 85,
    price: '$140.000',
    price_per_hour: 140000,
    image: '/pasto-pitch-collection.png',
    image_url: '/pasto-pitch-collection.png',
    tone: 'field-mint',
    amenity: 'Parqueadero',
    amenities: 'Parqueadero',
    open: true,
    surface: 'Sintética',
    size: '8 vs 8',
    created_at: new Date().toISOString()
  },
  {
    id: '3',
    company_id: '1',
    name: 'Las Palmas',
    type: 'Fútbol 5',
    zone: 'Centro',
    distance: '0.8 km',
    rating: '4.5',
    reviews: 42,
    price: '$85.000',
    price_per_hour: 85000,
    image: '/pasto-pitch-collection.png',
    image_url: '/pasto-pitch-collection.png',
    tone: 'field-emerald',
    amenity: 'Cafetería',
    amenities: 'Cafetería',
    open: false,
    surface: 'Sintética',
    size: '5 vs 5',
    created_at: new Date().toISOString()
  },
];

export const times = ['08:00', '09:30', '11:00', '14:00', '15:30', '17:00', '18:30', '20:00'];
